server:
  port: 0

api:
  port: '8080'
  host: localhost
  protocol: http

mail-service:
  port: '5321'
  endpoint: ${mail-service.protocol}://${mail-service.host}:${mail-service.port}/api/mail
  host: localhost
  protocol: http

activation:
  endpoint: ${api.protocol}://${api.host}:${api.port}/api/profile/auth/registration/activate

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/openhelp
    username: postgres
    password: 1
  jms:
    template:
      priority: 100
      qos-enabled: true
      time-to-live: 36000
      default-destination: empty
      receive-timeout: 1000
      delivery-mode: non_persistent
    listener:
      max-concurrency: 10
      concurrency: 5
      auto-startup: true
      acknowledge-mode: auto
    pub-sub-domain: false
  activemq:
    send-timeout: 0
    pool:
      max-connections: 1
      time-between-expiration-check: -1
      idle-timeout: 30000
      enabled: false
      use-anonymous-producers: true
      block-if-full: true
      block-if-full-timeout: -1
    close-timeout: 15000
    non-blocking-redelivery: false
    packages:
      trust-all: false
      trusted: com.domain
    in-memory: true
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    user: admin
    password: admin

logging:
  pattern:
    console: '%msg%n'
  level:
    org:
      springframework: info
    com:
      memorynotfound: debug