INSERT INTO access(is_read_role_list, is_read_own_role, is_create_role, is_update_role, is_delete_role,
                   is_read_user_list, is_read_any_user_details, is_read_any_user_action_log, is_create_user,
                   is_update_own_user, is_update_any_user, is_delete_own_user, is_delete_any_user,
                   is_read_sos_list, is_read_full_sos_list, is_read_any_sos_details, is_create_sos,
                   is_update_own_sos, is_update_any_sos, is_delete_own_sos, is_delete_any_sos,
                   is_read_story_list, is_read_full_story_list, is_read_any_story_details, is_create_story,
                   is_update_own_story, is_update_any_story, is_delete_own_story, is_delete_any_story,
                   is_read_group_list, is_read_full_group_list, is_read_any_group_detail,
                   is_send_group_request, is_send_group_invite, is_create_group, is_update_own_group,
                   is_update_any_group, is_delete_own_group, is_delete_any_group,
                   role_id)
VALUES (TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 4),
       (TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 3),
       (TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE,
        TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 2),
       (FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE,
        TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE,
        FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 1);
SELECT setval('access_id_seq', 4);