INSERT INTO access (id, title, entity_type, operation_type)
VALUES (1, 'Create new Role', 'ROLE', 'CREATE'),
       (2, 'Read own Role', 'ROLE', 'READ_OWN'),
       (3, 'Read any Role', 'ROLE', 'READ_ANY'),
       (4, 'Update own Role', 'ROLE', 'UPDATE_OWN'),
       (5, 'Update any Role', 'ROLE', 'UPDATE_ANY'),
       (6, 'Delete own Role', 'ROLE', 'DELETE_OWN'),
       (7, 'Delete any Role', 'ROLE', 'DELETE_ANY'),
       (8, 'Create new User', 'ROLE', 'CREATE'),
       (9, 'Read own User', 'USER', 'READ_OWN'),
       (10, 'Read any User', 'USER', 'READ_ANY'),
       (11, 'Update own User', 'USER', 'UPDATE_OWN'),
       (12, 'Update any User', 'USER', 'UPDATE_ANY'),
       (13, 'Delete own User', 'USER', 'DELETE_OWN'),
       (14, 'Delete any User', 'USER', 'DELETE_ANY'),
       (15, 'Create new Sos', 'SOS', 'CREATE'),
       (16, 'Read own Sos', 'SOS', 'READ_OWN'),
       (17, 'Read any Sos', 'SOS', 'READ_ANY'),
       (18, 'Update own Sos', 'SOS', 'UPDATE_OWN'),
       (19, 'Update any Sos', 'SOS', 'UPDATE_ANY'),
       (20, 'Delete own Sos', 'SOS', 'DELETE_OWN'),
       (21, 'Delete any Sos', 'SOS', 'DELETE_ANY'),
       (22, 'Create new Story', 'Story', 'CREATE'),
       (23, 'Read own Story', 'Story', 'READ_OWN'),
       (24, 'Read any Story', 'Story', 'READ_ANY'),
       (25, 'Update own Story', 'Story', 'UPDATE_OWN'),
       (26, 'Update any Story', 'Story', 'UPDATE_ANY'),
       (27, 'Delete own Story', 'Story', 'DELETE_OWN'),
       (28, 'Delete any Story', 'Story', 'DELETE_ANY'),
       (29, 'Create new Group', 'GROUP', 'CREATE'),
       (30, 'Read own Group', 'GROUP', 'READ_OWN'),
       (31, 'Read any Group', 'GROUP', 'READ_ANY'),
       (32, 'Update own Group', 'GROUP', 'UPDATE_OWN'),
       (33, 'Update any Group', 'GROUP', 'UPDATE_ANY'),
       (34, 'Delete own Group', 'GROUP', 'DELETE_OWN'),
       (35, 'Delete any Group', 'GROUP', 'DELETE_ANY');
SELECT setval('access_id_seq', 35);